CTSRD-CHERI/cheri-specification

.github/workflows/compile.yml

This should fix the current 404 we're seeing while trying to run CI.

Add apt-get update to CI build workflow

---

.gitignore
Makefile
cheri-architecture-tr.tex
cheri-architecture.tex

Add a cheri-architecture-tr.tex that defines an empty 'trformat'
command and then includes cheri-architecture.tex.  Modify
cheri-architecture.tex to use \ifdefined\trformat around blocks
specific to tech-report formatting.
With these changes, a tech-report formatted can always be built as
cheri-architecture-tr.pdf.  The default build only builds the normal
format.

Permit building both normal and tech-report formats.

---

chap-intro.tex
chap-model.tex

This fixes several small typos I spotted.

Fix typos in `chap-intro` and `chap-model`.

---

chap-architecture.tex
chap-cheri-riscv.tex

This is in response to an open comment @arichardson had on the earlier de-MIPS PR, but this paragraph was also missed in that PR and needs updating one way or another.

Qualify 32-bit vs 64-bit CHERI-RISC-V maturity.

---

app-cheri-128.tex
app-experimental.tex
chap-architecture.tex
glossary.tex
preamble.tex

This is more consistent with, for example, Permit_Seal gating use of CSeal.
Fixes #20

Rename Permit_CInvoke to Permit_Invoke.

---

chap-cheri-x86-64.tex
preamble.tex

This includes several changes:
- Use the flags field in the capability for CIP to define capability mode matching the approach used in CHERI-RISC-V rather than the D and B bits in the code and stack segment descriptors.  64-bit mode has already moved away from these bits for the most part, and Jess correctly noted that including the mode in the capability allows the encoding mode to be sealed.  This also means that flipping modes does not require far calls or jumps, just near absolute calls or jumps.
While here, define capability mode in a standalone section rather than as part of the capability addressing mode.
Add a subsection in the rationale section describing the old approach.
- Scrap the scheme to try to use segment prefixes to expand register selector fields for memory addressing. …

x86: Use flags for capmode and simplify CGS addressing.

---

chap-architecture.tex
chap-cheri-riscv.tex
chap-intro.tex
chap-isaref-riscv.tex
chap-model.tex
chap-rationale.tex

As previously discussed at length, move towards tag clearing on non-monotonic register-register operations in RISC-V and suggest it more strongly in general.
Currently this is just an initial cut at some text changes, which should likely be merged alongside the sail changes (https://github.com/CTSRD-CHERI/sail-cheri-riscv/pull/56) once validated in hardware.

Move from exceptions to tag clearing

---

chap-architecture.tex
chap-cheri-riscv.tex
chap-cheri-x86-64.tex

Move the tables out of the architecture chapter and into each architecture spec.  Morello already uses a different scheme for reporting exceptions that doesn't follow this code.
For RISC-V I moved the description of xtval out into a new subsection next to exception handling rather than being buried in a section about new CSRs.
For both RISC-V and x86-64 I have kept the existing values, but have condensed the tables slightly since they otherwise float several pages away.

Make the CHERI exception codes architecture-specific.

---

.github/workflows/compile.yml
.pre-commit-config.yaml
abstract.tex
app-exp-peripherals.tex
app-versions.tex
chap-assurance.tex
chap-historical.tex
chap-model.tex
chap-research.tex
cheri.bib
glossary.tex

To enable the hook, use `pip install --user pre-commit && pre-commit install`

Fix trailing whitespace and add a pre-commit hook

---

chap-cheri-x86-64.tex

Recommend deprecating these instructions in capability mode and not extending the immediate memory offsets to support capability immediates.

Add more prose on direct memory-offset MOVs.

---

chap-cheri-x86-64.tex

- Remove the unused 'None' value.
- Renumber tag violation first since to better match exception priority.
- Collapse error codes to remove gaps.

x86: Renumber capability fault error codes.

---

chap-cheri-x86-64.tex

If a CHERI instruction modifies any of the status flags in RFLAGS, claim that the other status flags are undefined so that the values do not have to be preserved.

x86: Mark other status flags in RFLAGS undefined.

---

chap-cheri-x86-64.tex

A 64-bit MOV instruction already provides this functionality due to the use of merged register files and little-endian in-memory capability format.

x86: Remove CGetAddr.

---

chap-cheri-x86-64.tex

Unsealed capabilities use a dedicated object type, so this instruction can be implemented by comparing the result of CGetType.

x86: Remove CGetSealed.

---

chap-cheri-riscv.tex
preamble.tex

This was originally part of #10 but has been split out into its own PR.
The Xstateen extension did not exist when the spec was written originally.  This moves the enable bit to make use of that extension and slightly expands the definition of what this bit would mean.  In QEMU we don't fully implement the bit (it's hardwired to on).  QEMU also implements additional bits for load-side barriers in xCCSR, so we might want to defer removing the register outright (should we document those bits?).

Move CHERI enable bit to [ms]envcfg.

---

.github/workflows/compile.yml

ubuntu-18.04 is no longer available and switching to latest avoids having to update this in the future.

Use ubuntu-latest for GitHub CI actions.

---

chap-rationale.tex

This almost certainly needs some rewording.  The first commit was my first stab at just trying to deprecate the instructions, but I think the prose there is rather thin and probably the last commit is a better starting point.  Probably the x86 chapter change should be pulled out of this and handled separately once we have consensus on this more general change.

Make DDC/PCC offsetting an optional feature rather than mandatory

---

chap-architecture.tex

This probably should have been in #34.

Remove references to PCC/DDC offseting in the architecture chapter.

---

chap-cheri-x86-64.tex

This assumes (and implicitly depends on) #34.

Remove offsetting from CHERI-x86

---

chap-cheri-x86-64.tex

Previously the sketch used this term for things that remained in 64-bit mode but were removed in capability mode.  However, the language wasn't always clear (e.g. in some cases it referred to instructions being deprecated in capability mode when they were in fact removed from in capability mode).  Mostly this replaces the uses of deprecate with remove.
Suggested-by: Jessica Clarke <jrtc27@jrtc27.com>

x86: Rework use of the term deprecate.

---

chap-cheri-x86-64.tex
chap-isaref-x86-64.tex
insn-x86-64/call.tex
insn-x86-64/jmp.tex
insn-x86-64/ret.tex

They are not needed to switch into 64-bit mode from capability mode and invalidating them removes the need to handle the awkward case of a far jump to a 32-bit segment from capability mode.
Note that IRET for exception return can still do a type of far branch.

x86: Remove far branches from capability mode.

---

app-experimental.tex
app-versions-7-0-alpha4.tex
chap-architecture.tex
chap-model.tex

Significantly reduces the number of warnings produced by the build - we are down to the following after this PR:
```
LaTeX Warning: Text page 31 contains only floats.
LaTeX Warning: `!h' float specifier changed to `!ht'.
LaTeX Warning: `!h' float specifier changed to `!ht'.
LaTeX Warning: Hyper reference `sailRISCVzMAX' on page 178 undefined on input l
LaTeX Warning: Hyper reference `sailRISCVzEzyFetchzyAddrzyAlign' on page 207 un
LaTeX Warning: Hyper reference `sailRISCVzEzyFetchzyAddrzyAlign' on page 209 un
LaTeX Warning: Hyper reference `sailRISCVzEzyFetchzyAddrzyAlign' on page 210 un
LaTeX Warning: Hyper reference `sailRISCVzcapszyperzycachezyline' on page 214 u
LaTeX Warning: Hyper reference `sailRISCVzEzyLoadzyAddrzyAlign' on page 214 und
LaTeX Warning: Hyper reference …
```

Fix most undefined references

---

insn-x86-64/gcbase.tex
insn-x86-64/gchi.tex
insn-x86-64/gclen.tex
insn-x86-64/gcoff.tex
insn-x86-64/gcperm.tex

There are probably not any hot paths that would need to optimize checking the result against zero.

x86: Don't set ZF for various GC* instructions.

---

chap-cheri-riscv.tex

This does not include any way to conditionally enable it though that could be added back in the future.  Mostly this is a draft to prompt further discussion.
Some interesting things: consistent with removing offsetting, this changes the description of SCRs that extend CSRs such that the CSR now reads/writes the address of the SCR rather than the offset.  Secondly, the discussion about unaligned PCC bases now very well all be moot without PCC offsetting (if PC is the address of PCC rather than the offset).  I've merely left a note about that rather than removing the section however.

RISC-V: Remove DDC/PCC offsetting entirely for now.

---

chap-cheri-riscv.tex

This does not explicitly mention JALR.DDC and JALR.CAP.

riscv: Update the main CHERI-RISC-V chapter for mode-dependent jumps.

---

chap-cheri-x86-64.tex
chap-isaref-x86-64.tex
preamble.tex

Prefixes for CS, DS, ES, and SS are already nops in 64-bit mode.  They are already treated as invalid for capability-aware addressing in both 64-bit mode and capability mode.  This commit extends that to integer addressing in capability mode.

x86: Deprecate most segment prefixes entirely in capability mode.

---

chap-cheri-riscv.tex

The current version of the privileged mode spec doesn't really refer to an S extension anymore.  Rather, it talks about supervisor and machine-level ISAs that serve as a base for that mode that can have optional extensions.

RISC-V: Tweak language for privileged mode.

---

app-experimental.tex
chap-cheri-riscv.tex
cheri.bib

While here, move the discussion of spec versions down to the section on CHERI as a RISC-V non-standard extension.

RISC-V: Claim to extend priv spec 1.11 instead of 1.10

---

acknowledgments.tex
app-experimental.tex
cheri-architecture.tex

This is an experimental section about Compartment IDs (CIDs) and how they can be used for implicit sealing.

Added CID Sealing section in experimental

---

chap-cheri-riscv.tex

CHERI-RISC-V's definition is more concrete with fewer alternatives than when the specification was first written.  The only remaining design space choice is 32-bit vs 64-bit which is probably not enough to justify the remaining language.  This does still keep the idea of a design space in the list of goals motivating the initial desire to apply CHERI to RISC-V as that list is largely historical.

RISC-V: Trim language around the CHERI ISA being a design space.

---

chap-rationale.tex

Shift the narrative of this section a bit more firmly to describe the separate register file on MIPS as the starting point and keep most of the existing text but framed as a series of steps that led to the merged register file approach currently used.  While here, also update some text in this section that speculated about adding CGetAddr to note that that CGetAddr was in fact added and explicitly reference it by name.

chap-rationale: Rewrite the capability register file section

---

cheri-architecture.tex

Use a bit of negative vspace to pull the title block up instead of shrinking the text.

Restore the funding acks to footnotesize

---

app-experimental.tex
cheri-architecture.tex
cheri.bib
preamble.tex

This describes the use of the Dirty CRG bit in sstatus as an extension to the standard RV64Y draft 2-bit PTE extension.

Experimental section on Two-phase revoker.
